### ISSUE TITLE
Which exactly Promise library is needed? 

### ISSUE THREAD

**Issue by OrKoN** [TakenPilot/gulp-static-handlebars#4]
I tried using https://github.com/jakearchibald/es6-promise and the example from the doc:

```
function getData() {
    return Promise.resolve({contents: 'whatever'});
}

function getHelpers() {
    return Promise.resolve({menu: function(options) { return 'menu!'; }});
}

function getPartials() {
    return Promise.resolve({header: '<header></header>', footer: '<footer></footer>'});
}

gulp.src('./app/index.hbs')
      .pipe(handlebars(getData(), {helpers: getHelpers(), partials: getPartials()}))
      .pipe(gulp.dest('./dist'));

```

And it didn't detect the helpers.

**Comment by TakenPilot** [comment]
Hmm, let me write a test for what you're doing with es6-promises and see what's happening.  Maybe I have to write better error handling to detect your situation.

It's doing duck-typing, so any object with a `.then` function is assumed to be a promise.

```js
function isPromise(obj) {
  return !!obj && _.isFunction(obj.then);
}
```

**Comment by TakenPilot** [comment]
@OrKoN Hey.

I tried that library, and everything seems to work.  I added unit tests to prove it in https://github.com/TakenPilot/gulp-static-handlebars/pull/5

So now all the promise tests are using bluebird and also https://github.com/jakearchibald/es6-promise, which is a very cool library.

I also added tests to handle `{someFn: {Promise.resolve(fn)}` and also `Promise.resolve({'someFn': fn})`.

If it's still failing, then you must have some kind of situation that I don't understand.  : )  Could you create a failing unit test to show me?

**Comment by OrKoN** [comment]
@TakenPilot Hey, thanks for looking into this. I've found the workaround but the initial problem still happens to me. See https://github.com/OrKoN/gulp-handlebars-static-test just clone, npm install and gulp.

My index template is:

```
Test

<h2> Test 2</h2>

{{menu}}
```

and the result is:

```
Test

<h2> Test 2</h2>


``
I.e. without `menu` should be printed by the menu helper.  I am running node 0.12.0 (installed the latest versions of everything from npm).

Maybe I mis-use the API but looks like it does not work to me. Also it does not work with native node promises (dunno if they are compliant).

**Comment by TakenPilot** [comment]
Ah!  The data is missing, not the helper.

**Comment by TakenPilot** [comment]
Hey, try this out:  https://github.com/OrKoN/gulp-handlebars-static-test/pull/1

I increased the npm version of this package as well to include partials that are promises in objects of strings.  I hadn't thought of that case.

Your code works for me now.  : )
